"""update placement jobs

Revision ID: 9559a58ebabd
Revises: 47203c169ca4
Create Date: 2026-07-11 19:00:59.240681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9559a58ebabd'
down_revision = '47203c169ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_id', sa.Integer(), nullable=False))
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('package',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('joining_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['application_id'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['student_id'])
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['user_id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('joining_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('package',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('application_id')

    # ### end Alembic commands ###
